/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vwtvivrkvrfewaalmica"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3dHZpdnJrdnJmZXdhYWxtaWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MTAwOTAsImV4cCI6MjA5MDI4NjA5MH0.4SEDnci0X-bNAco4Mee4X3nAKMMuEKAMM-6U11VrY80"